version: '3.7'
services:
  cassandra:
    container_name: cassandra
    image: cassandra:3
    env_file: .env
    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./cassandra-data:/var/lib/cassandra:cached
      - .:/app:cached
    ports:
      - 9042:9042
      - 9160:9160
      - 7000:7000
      - 7199:7199
    environment:
      - JVM_OPTS=-Xms1024M -Xmx1024M
